apiVersion: telemetry.istio.io/v1
kind: Telemetry

metadata:
  name: banking-tracing
  namespace: banking

spec:
  tracing:
    - providers:
        - name: jaeger

      randomSamplingPercentage: 100.0
