apiVersion: apps/v1
kind: Deployment
metadata:
  name: circuit-breaker-test
  namespace: banking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: circuit-breaker-test
  template:
    metadata:
      labels:
        app: circuit-breaker-test
    spec:
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: circuit-breaker-test
  namespace: banking
spec:
  selector:
    app: circuit-breaker-test
  ports:
    - name: http
      port: 80
      targetPort: 80
